version: '3.4'

services:
#  bookify.api:
#    image: ${DOCKER_REGISTRY-}bookifyapi
#    container_name: Bookify.API
#    build:
#      context: .
#      dockerfile: src/Bookify.API/Dockerfile
#    volumes:
#      - .:/app
#    command: ["dotnet", "watch","run", -v, "--project" , "src/Bookify.API/Bookify.API.csproj", "--urls", "https://*:443;http://*:80"]
#    depends_on:
#      - bookify-db
  
  bookify-db:
    image: postgres:16
    container_name: Bookify.Db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Abcd1234!
    volumes:
      - ./.container/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  bookify-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: Bookify.Identity
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: >
      start-dev --import-realm --hostname-strict=false
    volumes:
      - ./.container/identity:/opt/keycloak/data
      - ./.files/bookify-realm-export.json:/opt/keycloak/data/import/bookify-realm-export.json
    ports:
      - 18080:8080

  bookify-seq:
    image: datalust/seq:latest
    container_name: Bookify.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  bookify-redis:
    image: redis:latest
    container_name: Bookify.Redis
    restart: always
    ports:
      - 6379:6379
